version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      NODE_ENV: production
    command: sh -c "npm run migrate:up && npm start"
    restart: unless-stopped
