name: Deploy to Local Ubuntu

on:
  push:
    branches: [dev] # Rama de desarrollo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Local Ubuntu
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /ruta/a/tu/proyecto
            git pull
            docker-compose down
            docker-compose up -d
