name: Deploy to Local Ubuntu

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Local Ubuntu
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /mnt/c/Users/thuve/Documents/sqllite-nextjs
            git pull
            docker-compose down
            docker-compose up -d
